### ISSUE TITLE
User Auth feature

### ISSUE THREAD

**Issue by BBjie** [zylon-ai/private-gpt#1899]
I have seen they are auth.py file and auth settings in settings.yaml file, I'm assuming the auth feature is enabled in this project. Is there any guidance/documentation I can refer to to achieve it? 

**setting.yaml**
```
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: false
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
  auth:
    enabled: true
    # python -c 'import base64; print("Basic " + base64.b64encode("secret:key".encode()).decode())'
    # 'secret' is the username and 'key' is the password for basic auth by default
    # If the auth is enabled, this value must be set in the "Authorization" header of the request.
    secret: "Basic c2VjcmV0OmtleQ=="
```
